### ISSUE TITLE
How to Run ?

### ISSUE THREAD

**Issue by magadan** [omaha-consulting/winstall#101]
Hello, im trying to run, with 'npm run dev' i receive:

Oops!
Only absolute URLs are supported

How to run winstall? im using node version 17

Receive this on 'npm run build' : 

~/winstall# npm run build

`
info  - Creating an optimized production build .(node:7727) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
[    ] info  - Generating static pages (0/13)Only absolute URLs are supported
Only absolute URLs are supported
Only absolute URLs are supported

Error occurred prerendering page "/packs/edit". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Error serializing `.allApps` returned from `getStaticProps` in "/packs/edit".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
    at isSerializable (/root/winstall/node_modules/next/dist/lib/is-serializable-props.js:30:19)
    at /root/winstall/node_modules/next/dist/lib/is-serializable-props.js:37:66
    at Array.every (<anonymous>)
    at isSerializable (/root/winstall/node_modules/next/dist/lib/is-serializable-props.js:34:39)
    at Object.isSerializableProps (/root/winstall/node_modules/next/dist/lib/is-serializable-props.js:57:12)
    at renderToHTML (/root/winstall/node_modules/next/dist/server/render.js:521:93)
    at async /root/winstall/node_modules/next/dist/export/worker.js:269:36
    at async Span.traceAsyncFn (/root/winstall/node_modules/next/dist/trace/trace.js:75:20)

Error occurred prerendering page "/packs/create". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Error serializing `.allApps` returned from `getStaticProps` in "/packs/create".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
    at isSerializable (/root/winstall/node_modules/next/dist/lib/is-serializable-props.js:30:19)
    at /root/winstall/node_modules/next/dist/lib/is-serializable-props.js:37:66
    at Array.every (<anonymous>)
    at isSerializable (/root/winstall/node_modules/next/dist/lib/is-serializable-props.js:34:39)
    at Object.isSerializableProps (/root/winstall/node_modules/next/dist/lib/is-serializable-props.js:57:12)
    at renderToHTML (/root/winstall/node_modules/next/dist/server/render.js:521:93)
    at async /root/winstall/node_modules/next/dist/export/worker.js:269:36
    at async Span.traceAsyncFn (/root/winstall/node_modules/next/dist/trace/trace.js:75:20)
info  - Generating static pages (13/13)

> Build error occurred
Error: Export encountered errors on following paths:
        /packs/create
        /packs/edit
    at /root/winstall/node_modules/next/dist/export/index.js:498:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/root/winstall/node_modules/next/dist/trace/trace.js:75:20)
    at async /root/winstall/node_modules/next/dist/build/index.js:1024:17
    at async Span.traceAsyncFn (/root/winstall/node_modules/next/dist/trace/trace.js:75:20)
    at async /root/winstall/node_modules/next/dist/build/index.js:898:13
    at async Span.traceAsyncFn (/root/winstall/node_modules/next/dist/trace/trace.js:75:20)
    at async Object.build [as default] (/root/winstall/node_modules/next/dist/build/index.js:82:25)
`

**Comment by st-jliu** [comment]
You can copy the '.env.example' as '.env' and replace the config in it before you try to compile the website.

Suspect you are treating the site's source code as a CLI tool, unfortunatly it is not. But however, I still hope this information proves helpful in some way.

And this project was taken over by Splashtop now, we will continue the development and maintenance, you are welcome to provide further feedback and suggestions.
